### ISSUE TITLE
When I try to load pdf from online it return me this error

### ISSUE THREAD

**Issue by ziasultan2** [lohanidamodar/pdf_viewer#10]
I'm getting error when I try to load pdf from online. I attatched my code and error below. Please check and let me know the solution
### **code**
import 'package:advance_pdf_viewer/advance_pdf_viewer.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
```
class TestDetail extends StatefulWidget {
  String path;
  TestDetail(this.path);
  @override
  _TestDetailState createState() => _TestDetailState();
}

class _TestDetailState extends State<TestDetail> {
  bool _isLoading = true;
  PDFDocument document;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    loadDocument();
  }

  loadDocument() async {
    print(widget.path);
    document = await PDFDocument.fromURL(widget.path);
    setState(() => _isLoading = false);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test Detail'),
      ),
      body: Container(
          child: _isLoading
              ? Center(
                  child: CupertinoActivityIndicator(),
                )
              : PDFViewer(
                  document: document,
                  zoomSteps: 1,
                )),
    );
  }
}
```
### **Error** 

```[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:26:52)
#1      _PDFViewerState._loadPage (package:advance_pdf_viewer/src/viewer.dart:140:15)
#2      _PDFViewerState.didChangeDependencies (package:advance_pdf_viewer/src/viewer.dart:119:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4705:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:<…>
```

**Comment by lohanidamodar** [comment]
1. Is this a complete error? Don't see what's the problem from the error message
2. Have you verified the url is a valid PDF? can you share the URL?

**Comment by osamasado** [comment]
I have the same issue, have you any solution?
