### ISSUE TITLE
The application crashes when I try to download a pdf file from assets (Android)

### ISSUE THREAD

**Issue by Al-Krause-ex** [lohanidamodar/pdf_viewer#110]
When I load a pdf file from assets, my application crashes. The PDF file is 2 MB.

The code:
`import 'package:advance_pdf_viewer/advance_pdf_viewer.dart';`
`import 'package:flutter/material.dart';`

``
class PdfPage extends StatefulWidget {
  const PdfPage({Key? key}) : super(key: key);
``

`  @override`
`  _PdfPageState createState() => _PdfPageState();`
`}`

`class _PdfPageState extends State<PdfPage> {`
`  PDFDocument? doc;`
`  var isLoading = false;`

`  @override`
`  void initState() {`
`    isLoading = true;`
`    loadDoc();`
`    super.initState();`
`  }`

``
  Future loadDoc() async {
    doc = await PDFDocument.fromAsset('assets/pdfs/screen.pdf');
    setState(() {
      isLoading = false;
    });
  }
``
`  @override`
`  Widget build(BuildContext context) {`
`    return Scaffold(`
`        body: Center(`
`      child: isLoading`
`          ? const CircularProgressIndicator()`
`          : PDFViewer(document: doc!),`
`    ));`
`  }`
`}`

Mistake:
> I/System.out(17782): Already closed
W/System.err(17782): java.lang.IllegalStateException: Already closed
W/System.err(17782): 	at android.graphics.pdf.PdfRenderer.throwIfClosed(PdfRenderer.java:270)
W/System.err(17782): 	at android.graphics.pdf.PdfRenderer.close(PdfRenderer.java:187)
W/System.err(17782): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.getPage(FlutterPluginPdfViewerPlugin.java:206)
W/System.err(17782): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.access$100(FlutterPluginPdfViewerPlugin.java:31)
W/System.err(17782): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:84)
W/System.err(17782): 	at android.os.Handler.handleCallback(Handler.java:888)
W/System.err(17782): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(17782): 	at android.os.Looper.loop(Looper.java:213)
W/System.err(17782): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/PdfViewerPlugin(17782): Retrieving page failed.
D/AndroidRuntime(17782): Shutting down VM
I/QarthLog(17782): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(17782): [PatchStore] create disable file for com.example.pdf_check uid is 10661
E/AndroidRuntime(17782): FATAL EXCEPTION: main
E/AndroidRuntime(17782): Process: com.example.pdf_check, PID: 17782
E/AndroidRuntime(17782): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(17782): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(17782): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:264)
E/AndroidRuntime(17782): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1$2.run(FlutterPluginPdfViewerPlugin.java:92)
E/AndroidRuntime(17782): 	at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime(17782): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17782): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(17782): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(17782): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17782): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(17782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter (17782): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getPage on channel flutter_plugin_pdf_viewer)
E/flutter (17782): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (17782): <asynchronous suspension>
E/flutter (17782): #1      PDFDocument.get (package:advance_pdf_viewer/src/document.dart:97:18)
E/flutter (17782): <asynchronous suspension>
E/flutter (17782): #2      _PDFViewerState._loadPage (package:advance_pdf_viewer/src/viewer.dart:151:18)
E/flutter (17782): <asynchronous suspension>
E/flutter (17782): 
I/Process (17782): Sending signal. PID: 17782 SIG: 9

**Comment by SureshKumar311** [comment]
for me too

**Comment by brahimchebbi** [comment]
for me too

**Comment by mhabashy** [comment]
Me too

**Comment by Izudinalqasam** [comment]
me too, is there any fix ?

**Comment by maulik-intent-labs** [comment]
I am using this `PDFDocument.fromURL(documentURL).` and getting the same issue with my Android device. iOS device works well.

**Comment by 877209649** [comment]
me too

**Comment by amosesuwali** [comment]
Same Here

**Comment by Dakrain** [comment]
Any update? I am getting the same issue too.

**Comment by chunsehun** [comment]
I have same issues...

**Comment by jhuhandha** [comment]
I have same issues with fromURL()

**Comment by xobe19** [comment]
same issues!

**Comment by anandsubbu007** [comment]
any update

**Comment by btraas** [comment]
Same here

**Comment by CrownKingClown** [comment]
Same here

**Comment by ramonpaolo** [comment]
same problem here!

**Comment by ChurikiTenna** [comment]
same

**Comment by EArminjon2** [comment]
same here

**Comment by madhanKMani** [comment]
did any one find the solution for this issue?

**Comment by ramonpaolo** [comment]
I changed the lib `pdf_viewer` to `pdf_render`

**Comment by ysnky** [comment]
same

**Comment by vietstone-ng** [comment]
I use the previous version (2.0.0) as this Stackoverflow answer, then it work
https://stackoverflow.com/a/71226926/566360

**Comment by anandyadav21219** [comment]
same issue

**Comment by frankperez87** [comment]
Seems like Version 2.0.2 solved the issue for me. I posted what I did here.

https://github.com/lohanidamodar/pdf_viewer/issues/117
