### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by liusilong** [lohanidamodar/pdf_viewer#114]
E/AndroidRuntime(15736): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(15736): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:286)
E/AndroidRuntime(15736): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(15736): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1$2.run(FlutterPluginPdfViewerPlugin.java:92)
E/AndroidRuntime(15736): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(15736): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15736): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(15736): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(15736): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(15736): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15736): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(15736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (15736): Sending signal. PID: 15736 SIG: 9

**Comment by hamza-bilal-gaya** [comment]
This plugin is being crashing on android on any device with this error in below screenshot.  I think on android there is some native configuration missing for android main manifest file. As I am not a native android developer, I cannot identify this error I hope you'll resolve this error in the next version of this package.
![Screenshot 2022-09-15 at 12 47 19 PM (2)](https://user-images.githubusercontent.com/84728933/190346562-d1490176-164d-430e-879b-c1e30cd5db75.png)

**Comment by liusilong** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by frankperez87** [comment]
Seems like Version 2.0.2 solved the issue for me. I posted what I did here.

https://github.com/lohanidamodar/pdf_viewer/issues/117

**Comment by shahadat-polygon** [comment]
```
 advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722 
```

It's working for me.
