### ISSUE TITLE
Unhandled Exception: Exception: Error reading PDF!

### ISSUE THREAD

**Issue by abdullah4one** [lohanidamodar/pdf_viewer#14]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Error reading PDF!
E/flutter ( 8299): #0      PDFDocument.fromURL (package:advance_pdf_viewer/src/document.dart:52:7)
E/flutter ( 8299): <asynchronous suspension>
E/flutter ( 8299): #1      _PdfPageState.loadPdf (package:store/pages/pdf_page.dart:51:32)
E/flutter ( 8299): #2      _PdfPageState.initState (package:store/pages/pdf_page.dart:20:5)
E/flutter ( 8299): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 8299): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 8299): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 8299): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 8299): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 8299): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 8299): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 8299): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 8299): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 8299): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 8299): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 8299): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 8299): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 8299): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 8299): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 8299): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 8299): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 8299): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 8299): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 8299): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 8299): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 8299): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 8299): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 8299): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 8299): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 8299): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 8299): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 8299): #46     ComponentEl

**Comment by lohanidamodar** [comment]
Error reading PDF usually means the PDF document is not valid, this could mean, you have provided invalid path or you don't have access to that path or the document itself is invalid.

**Comment by alien142** [comment]
I have same issue, I open url on browser, it's exists

**Comment by AhmedAbogameel** [comment]
i have the same issue it's working on debug on release not working
