### ISSUE TITLE
Loading document from Url is throwing exception.

### ISSUE THREAD

**Issue by mahendary** [lohanidamodar/pdf_viewer#19]
Loading document from Url is throwing below exception.

`======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building _BodyBuilder:
The getter 'count' was called on null.
Receiver: null
Tried calling: count

The relevant error-causing widget was: 
  Scaffold file:///Users/kh369/Desktop/Mahi/PersonalWork/Mihy/Src/mihy/lib/Forms/viewAttachement.dart:58:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _PDFViewerState.initState (package:advance_pdf_viewer/src/viewer.dart:99:35)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4812:57)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
...     Normal element mounting (19 frames)
...
====================================================================================================`

**Comment by budescode** [comment]
I'm having same issue
